In [1]:
import pandas as pd
import matplotlib.pyplot as plt

import openpyxl
from openpyxl import load_workbook

from kmodes.kmodes import KModes

In [2]:
wb = load_workbook('dataset_usaha.xlsx');
sheet = wb['main']

In [3]:
data = []

for row in sheet.iter_rows(values_only=True):
    data.append(row)

# Convert the list of data into a DataFrame
df = pd.DataFrame(data)

In [4]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,No.,Nib,Npwp Perusahaan,Nama Perusahaan,Uraian Status Penanaman Modal,Uraian Jenis Perusahaan,Uraian Risiko Proyek,nama_proyek,Uraian Skala Usaha,Alamat Usaha,kecamatan_usaha,kelurahan_usaha,Kbli,Judul Kbli,Nama User,Nomor Identitas User,Nomor Telp
1,1,9120018051443,906904768824000,APOTEK TOKIN INTI SEJAHTERA,PMDN,Perorangan,Tinggi,Apotek Tokin Inti Sejahtera,Usaha Mikro,"Apotek Tokin Inti Sejahtera, Jln. Trans Sulawesi",Amurang,Uwuran II,47721,Perdagangan Eceran Barang Dan Obat Farmasi Unt...,CHRISTINE SETIAWATI,7105176704840001,082243882000
2,2,9120200932569,141501502824000,INDRA MOTOR,PMDN,Perorangan,Menengah Rendah,INDRA MOTOR,Usaha Mikro,LINGKUNGAN VII,Amurang,Buyungon,45201,Reparasi Mobil,JOHANIS LOING,7105102307750001,82192069909
3,3,9120200932569,141501502824000,INDRA MOTOR,PMDN,Perorangan,Rendah,INDRA MOTOR,Usaha Mikro,LINGKUNGAN VII,Amurang,Buyungon,45302,Perdagangan Eceran Suku Cadang Dan Aksesori Mobil,JOHANIS LOING,7105102307750001,82192069909
4,4,8120115030514,857446868824000,JOBUBU SUKSESRAYA DISTRIBUSI,PMDN,Perseroan Terbatas (PT),Tinggi,PT. Jobubu Suksesraya Distribusi,Usaha Besar,Jl. Kapitu,Amurang Barat,Kapitu,46333,Perdagangan Besar Minuman Beralkohol,JOKO HADI NUGROHO,3671092811630001,0431852222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737,5.737,0404230015782,751442286824000,NUSANTARA JAYA MANDIRI,PMDN,Persekutuan Komanditer (CV / Commanditaire Ven...,Rendah,NUSANTARA JAYA MANDIRI,Usaha Mikro,TANAMON JAGA V,Sinonsayang,Tanamon,46319,Perdagangan Besar Bahan Makanan Dan Minuman Ha...,NURKHOLIS KAU,7105082909860001,081356179316
5738,5.738,0404230015782,751442286824000,NUSANTARA JAYA MANDIRI,PMDN,Persekutuan Komanditer (CV / Commanditaire Ven...,Tinggi,NUSANTARA JAYA MANDIRI,Usaha Mikro,TANAMON JAGA V,Sinonsayang,Tanamon,46447,Perdagangan Besar Bahan Farmasi Untuk Manusia ...,NURKHOLIS KAU,7105082909860001,081356179316
5739,5.739,0404230015782,751442286824000,NUSANTARA JAYA MANDIRI,PMDN,Persekutuan Komanditer (CV / Commanditaire Ven...,Tinggi,NUSANTARA JAYA MANDIRI,Usaha Mikro,TANAMON JAGA V,Sinonsayang,Tanamon,46447,Perdagangan Besar Bahan Farmasi Untuk Manusia ...,NURKHOLIS KAU,7105082909860001,081356179316
5740,5.740,0404230045403,147243976824000,PATRIS INDRA PAAT,PMDN,Perorangan,Rendah,UD. Tondei Mandiri,Usaha Kecil,Jaga V,Motoling Barat,Tondei Satu,47112,Perdagangan Eceran Berbagai Macam Barang Yang ...,PATRIS INDRA PAAT,7105216404760001,+
5741,5.741,0404230045403,147243976824000,PATRIS INDRA PAAT,PMDN,Perorangan,Rendah,UD. Tondei Mandiri,Usaha Kecil,Jaga V,Motoling Barat,Tondei Satu,47528,Perdagangan Eceran Berbagai Macam Material Ban...,PATRIS INDRA PAAT,7105216404760001,+

In [5]:
df.columns = df.iloc[0]

In [6]:
df.dtypes

0
No.                              object
Nib                              object
Npwp Perusahaan                  object
Nama Perusahaan                  object
Uraian Status Penanaman Modal    object
Uraian Jenis Perusahaan          object
Uraian Risiko Proyek             object
nama_proyek                      object
Uraian Skala Usaha               object
Alamat Usaha                     object
kecamatan_usaha                  object
kelurahan_usaha                  object
Kbli                             object
Judul Kbli                       object
Nama User                        object
Nomor Identitas User             object
Nomor Telp                       object
dtype: object

In [7]:
df = df.drop(0)

In [8]:
df = df.drop('No.', axis=1)

In [9]:
df.columns

Index(['Nib', 'Npwp Perusahaan', 'Nama Perusahaan',
       'Uraian Status Penanaman Modal', 'Uraian Jenis Perusahaan',
       'Uraian Risiko Proyek', 'nama_proyek', 'Uraian Skala Usaha',
       'Alamat Usaha', 'kecamatan_usaha', 'kelurahan_usaha', 'Kbli',
       'Judul Kbli', 'Nama User', 'Nomor Identitas User', 'Nomor Telp'],
      dtype='object', name=0)

In [10]:
df_target_cluster =  df[['Uraian Jenis Perusahaan', 'Uraian Risiko Proyek', 'Uraian Skala Usaha', 'Kbli']]

In [11]:
df_target_cluster

,Uraian Jenis Perusahaan,Uraian Risiko Proyek,Uraian Skala Usaha,Kbli
1,Perorangan,Tinggi,Usaha Mikro,47721
2,Perorangan,Menengah Rendah,Usaha Mikro,45201
3,Perorangan,Rendah,Usaha Mikro,45302
4,Perseroan Terbatas (PT),Tinggi,Usaha Besar,46333
5,Perseroan Terbatas (PT),Rendah,Usaha Besar,52101
...,...,...,...,...
5737,Persekutuan Komanditer (CV / Commanditaire Ven...,Rendah,Usaha Mikro,46319
5738,Persekutuan Komanditer (CV / Commanditaire Ven...,Tinggi,Usaha Mikro,46447
5739,Persekutuan Komanditer (CV / Commanditaire Ven...,Tinggi,Usaha Mikro,46447
5740,Perorangan,Rendah,Usaha Kecil,47112
5741,Perorangan,Rendah,Usaha Kecil,47528

df_target_cluster[df_target_cluster['Uraian Risiko Proyek'] == 'Tinggi'].head(20)

df_target_cluster[df_target_cluster['Uraian Jenis Perusahaan'] == 'Tinggi']

df['Uraian Jenis Perusahaan'].describe()

df['Uraian Jenis Perusahaan'].unique()

df_target_cluster[df_target_cluster['Uraian Jenis Perusahaan'] == 'Perorangan'].describe()

In [12]:
df_target_cluster

,Uraian Jenis Perusahaan,Uraian Risiko Proyek,Uraian Skala Usaha,Kbli
1,Perorangan,Tinggi,Usaha Mikro,47721
2,Perorangan,Menengah Rendah,Usaha Mikro,45201
3,Perorangan,Rendah,Usaha Mikro,45302
4,Perseroan Terbatas (PT),Tinggi,Usaha Besar,46333
5,Perseroan Terbatas (PT),Rendah,Usaha Besar,52101
...,...,...,...,...
5737,Persekutuan Komanditer (CV / Commanditaire Ven...,Rendah,Usaha Mikro,46319
5738,Persekutuan Komanditer (CV / Commanditaire Ven...,Tinggi,Usaha Mikro,46447
5739,Persekutuan Komanditer (CV / Commanditaire Ven...,Tinggi,Usaha Mikro,46447
5740,Perorangan,Rendah,Usaha Kecil,47112
5741,Perorangan,Rendah,Usaha Kecil,47528

In [14]:
kmode = KModes(n_clusters=num_clusters, init = "random", n_init = 5, verbose=1)
kmode.fit_predict(df_target_cluster)

TypeError: '<' not supported between instances of 'int' and 'str'

In [13]:
cost = []
K = range(1,5)
for num_clusters in list(K):
    kmode = KModes(n_clusters=num_clusters, init = "random", n_init = 5, verbose=1)
    kmode.fit_predict(df_target_cluster)
    cost.append(kmode.cost_)
    
plt.plot(K, cost, 'bx-')
plt.xlabel('No. of clusters')
plt.ylabel('Cost')
plt.title('Elbow Method For Optimal k')
plt.show()

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:
kmode = KModes(n_clusters=2, init = "random", n_init = 5, verbose=1)
clusters = kmode.fit_predict(df_target_cluster)
clusters

In [ ]:
df_cluster_result = df_target_cluster.copy()

In [ ]:
df_cluster_result['cluster'] = clusters

In [ ]:
df_cluster_result

In [ ]:
df_cluster_result[df_cluster_result['cluster'] == 0]

In [ ]:
df_cluster_result[df_cluster_result['cluster'] == 1]

In [ ]:
df_target_cluster

SyntaxError: invalid syntax (1379665737.py, line 1)